package cz.bernhard.playground.cv;

/**
 * 
 * Levels of skills.
 * 
 * @author Michal Bernhard (michal@bernhard.cz)
 *
 */
public enum Level {
	
	/**
	 * WRITE HELLO WORLD APP AND READ "JAVA" BOOK FROM HEROUT
	 */
	BEGINNER, 
	
	/**
	 * I CAN RUN UNIT TESTS AND KNOW THERE IS SOME BEAST CALLED GARBAGE COLLECTOR WHICH DO SOMETHING WITH MEMORY
	 * ALTHOUGHT I DO NOW KNOW WHAT MEMORY 
	 */
	INTERMEDIATE,
	
	/**
	 * I CAN RUN REMOTE DEBUGGER, MESS AROUND CODE AND FIND SOLUTION AS LONG AS IT'S NOT SOME HARDCORE STUFF
	 * LIKE GC PAUSES, MEMORY LEAK DURING CALL OF NATIVE CODE, JAVA BYTECODE MANIPULATION OR ANTLR PARSER.
	 */
	ADVANCED,
	
	/**
	 * YOU CAN'T CALL EXPERT YOURSELF, OTHERS DO! FOR EXAMPLE WHEN YOU WRITE ANTLR GRAMMARS AT NIGHTS JUST FOR
	 * YOUR FUN. YOU'RE PROBABLY ASOCIAL DEVIANT AND YOUR FAVORITE SUPER HERO IS DEXTER MORGAN.  
	 */
	EXPERT

}
